### ISSUE TITLE
[BE] Implement cosmetics data crawling

### ISSUE THREAD

**Issue by LBC11** [jeewonkimm2/capstone#1]
## 📝 Description
Implement a web scraper to collect and organize data on various cosmetics products from www.sephora.com. This will help us to build a comprehensive database of cosmetics products for our model.

## 🌟 Tasks
- [ ] Research the website's structure to determine the best scraping strategy.
- [ ] Set up a scraping tool or library
- [ ] Design the data model for storing the scraped data.
- [ ] Implement data cleaning methods to refine and structure the scraped data.
- [ ] Store the cleaned data in our designated database.
