### ISSUE TITLE
[BE] Deploy the server on AWS environment

### ISSUE THREAD

**Issue by LBC11** [jeewonkimm2/capstone#4]
## 📝 Description
Deploy our constructed server on AWS to ensure scalability, reliability, and ease of maintenance. Using AWS services will allow us to leverage cloud-based tools for better performance.

## 🌟 Tasks
- [ ] Evaluate the best AWS services for our server needs
- [ ] Set up an AWS account and configure necessary IAM roles and permissions.
- [ ] Configure the server for production
- [ ] Set up AWS EC2 instance or other relevant services.
- [ ] Deploy the server code and dependencies onto the AWS environment.
- [ ] Ensure security groups, VPC, and other networking configurations are set for secure communication.
- [ ] Set up a domain pointing to the AWS instance
